

###  Constants

BENIGN = 50
TOTAL_SEGMENTS = 150
USER = '0'
USER_COUNT = 40
TRAIN_USER_COUNT = 10


### What features to collect:
ENABLE_IMPERSONATOR_COMMANDS = True
ENABLE_NEW_COMMANDS = True
ENABLE_COMMON_COMMANDS = True
ENABLE_DUPLICATE_COMMANDS = True
ENABLE_REPEATED_PATTERNS = True

